name: cc-ssl-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.10
  
  # Core scientific computing
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  
  # Machine Learning
  - scikit-learn>=1.0.0
  
  # Data access
  - openml>=0.12.0
  
  # Visualization
  - matplotlib>=3.4.0
  
  # Optional: for improved performance
  - joblib>=1.1.0
  
  # Development tools
  - pip
  - pytest

# To create this environment:
# conda env create -f requirements.yml
#
# To activate:
# conda activate cc-ssl-env
#
# To update:
# conda env update -f requirements.yml
